### ISSUE TITLE
Location of environment req's

### ISSUE THREAD

**Issue by kcpevey** [Quansight/omnisci-datascience-installer#14]
The constructor yaml which generates this installer package is not the same as an `environment.yml`. In the conda installation instructions for this repo, we’re pointing to the `omnisci-examples` repo for the `environment.yml` to build off of. Which means the constructor yml will need to be maintained to match.

Seems like we’re doing this backwards. I think we need to move the `environment.yml` from `omnisci-examples` into this repo and then see if there is a way to link to that file in the constructor yaml so we don’t have to maintain two files. 

@xmnlab @scopatz Thoughts or opinions?

**Comment by xmnlab** [comment]
Maybe it would be good if we create a conda meta package that adds all the dependencies for the omnisci-datascience stack. So it would be easy for the instructions and also for keeping just a place with the dependencies.

@scopatz any thoughts about this?

**Comment by dharhas** [comment]
`conda meta package` -> this just changes the location of the yaml file. we still need a yaml file somewhere.

**Comment by scopatz** [comment]
Constuctor can take an environment_file key now https://github.com/conda/constructor/blob/master/CONSTRUCT.md#environment_file. However, this may not be desirable to be the same as the one you want to use in other contexts, namely because conda itself needs to be included for the pkg installer.

**Comment by kcpevey** [comment]
@scopatz Is it possible to combine an `environment_file` key with a `specs` key? So we could keep a "clean" environment file and then add in the constructor extras as `specs`?

Other ideas on how to resolve this?

**Comment by scopatz** [comment]
They are mutually exclusive right now.  There is no way to layer them, though that could be added to constructor I suppose.  I guess the best way to solve this with code-in-hand now is to just have a single env file with all deps.

**Comment by dharhas** [comment]
Let's not over think this. After the workshop, things are going to go dormant for a while so it isn't like we need to update these yaml files a lot. Adding some docs in the readme of what needs to be updated when might be enough.

**Comment by kcpevey** [comment]
The ds installer now runs off of an `environment.yml`. I say we just copy that file into the `omnisci-examples` repos. @xmnlab is this something you have time for?

**Comment by xmnlab** [comment]
maybe next week I can work on that.

**Comment by kcpevey** [comment]
This has been done.
