### ISSUE TITLE
update requirements yaml and rebuild package

### ISSUE THREAD

**Issue by dharhas** [Quansight/omnisci-datascience-installer#2]
- Update to Omnisci 5.4
- Updates needed by Ibis/Holoviews etc

@xmnlab can you help @kcpevey on this. This should happen after https://github.com/Quansight/omnisci-examples is updated

**Comment by kcpevey** [comment]
The ibis-hv update is still in PR https://github.com/holoviz/holoviews/pull/4517 . The OmniSci 5.4 update can  be tested by using the latest omnisci docker container. The mac preview hasn't been updated for 5.4 yet.

**Comment by xmnlab** [comment]
The package is updated and released (https://github.com/Quansight/omnisci-datascience-installer/releases/tag/0.0.4)

The notebook 3 from the example repo was tested with success.
The mac preview also was tested using the `sh` installer with success.

**Comment by kcpevey** [comment]
I had to make some updates for the presentation. Here are some notes on the additional stuff I had to use:

* holoviews from PR https://github.com/holoviz/holoviews/pull/4517
* ibis - from commit `10d40305defc7337d217b595c4b6b74e66d153da`
* hvplot from PR https://github.com/holoviz/hvplot/pull/507
* python-graphviz
* pydot
* geoviews ( will pull in holoviews which you'll have to manually remove with `--force`)

**Comment by xmnlab** [comment]
ok @kcpevey I will update the recipe for that. thanks!

**Comment by kcpevey** [comment]
This has been completed.
