### ISSUE TITLE
Mac Package Installer hits Security Block under Catalina

### ISSUE THREAD

**Issue by mflaxman10** [Quansight/omnisci-datascience-installer#22]
Ran into this upon attempt to install under Catalina (10.15.4), new system default security settings:

![image](https://user-images.githubusercontent.com/2546667/96942187-47a4f480-1489-11eb-9acc-45498c9a3e58.png)

<img width="372" alt="image" src="https://user-images.githubusercontent.com/2546667/96942171-3825ab80-1489-11eb-93c7-a935eeb86a19.png">

**Comment by dharhas** [comment]
The .pkg version of the installer is currently non functional because of changes in Catalina and we are waiting for the upstream conda constructor to catch up. In the meantime the command line bash installer is what needs to be used.

**Comment by mflaxman10** [comment]
According to this site:
https://howtoremove.guide/macos-cannot-verify/

" With the Catalina update, there’s an additional safety requirement for apps that are from out of the store – they need to be notarized by Apple."

Relevant Apple docs are here:

https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution

**Comment by dharhas** [comment]
There are other problems with the .pkg installer unrelated to this issue. This one has a workaround.

**Comment by mflaxman10** [comment]
Update Feb 2021 - same issue confirmed to affect "Big Sur" as well.   The workaround available is not clearly documented by Apple, and has changed over time between OS versions.  So if we're going to use a "doc fix" we'll need to careful version-specific docs.  By default, people will get stuck on this and the next step is not at all obvious.

**Comment by xmnlab** [comment]
@mflaxman10 IIRC the package has being signed manually (not part of the CI jobs). So I guess it is not a problem anymore, right?
maybe next step for that would be to move omnisci-datascience-installer to OmniSci github organization and sign the package on  CI.

let me know if there is anything we can do about that or if there is anything else missing about this issue.
