### ISSUE TITLE
Missing ibis-vega-transform in DS installer package 0.1.0?

### ISSUE THREAD

**Issue by niviksha** [Quansight/omnisci-datascience-installer#48]
Seems like `ibis-vega-trasnform` is no longer installed in the latest DS installer build, causing all ibis+Altair charts and notebooks to break

**Comment by niviksha** [comment]
trying with 0.1.5, get this
<img width="1526" alt="image" src="https://user-images.githubusercontent.com/277439/108147390-9e12f000-7083-11eb-80d4-22f66e2d560e.png">

**Comment by xmnlab** [comment]
Thanks for the feedback.
Which notebook  are you using?
Are you using sh or pkg installer?
