### ISSUE TITLE
Fix issue with already-installed conda

### ISSUE THREAD

**Issue by niviksha** [Quansight/omnisci-datascience-installer#49]
The pkg installer fails if there's an already installed conda with the message 'You should run conda update'. Ideally we would want to do that under the hood and create just the conda env if this is the case (i.e on top of the existing conda install).

**Comment by xmnlab** [comment]
Hi @niviksha I have a beta conda package that maybe could be used. I am still testing that ... and it takes around 10 minutes just to resolve the package dependency graph

**Comment by niviksha** [comment]
ah - is it stuck on pyarrow or pymapd?

**Comment by xmnlab** [comment]
I think it is because currently ibis is pinning pymapd 0.24 ... maybe if we could have a release for ibis-omnisci ... the dependency resolve would be much better ... I can check what would be necessary for that.

**Comment by xmnlab** [comment]
for conda update, probably the best way to go now is to install `omnisci-data-science-tools` and `omnisci-notebooks-examples`.
the link for the notebooks needs to be done manually (inside the conda environment):

```sh
ln -s ${CONDA_PREFIX}/opt/omnisci-examples ${HOME}/Documents/
```
