### ISSUE TITLE
Investigate installer support for Linux

### ISSUE THREAD

**Issue by israelvicars** [Quansight/omnisci-datascience-installer#57]
There is interest in extending the installer's support to Linux for use with OmniSci Free edition. Please investigate the work required to extend the installer for a new OS.

Corresponding integration investigation task: https://omnisci.atlassian.net/browse/FE-13235

**Comment by dharhas** [comment]
This should be straightforward. Linux support is typically much simpler than OSX and Windows. 

From the docs:

```
installer_type
required: no
types: string, list
The type of the installer being created. Possible values are:

sh: shell-based installer for Linux or macOS;
pkg: macOS GUI installer
exe: Windows GUI installer

The default type is sh on Linux and macOS, and exe on Windows. A special value of all builds both sh and pkg installers on macOS, as well as sh on Linux and exe on Windows.
```

It looks like the linux installer *is* the bash installer.

**Comment by xmnlab** [comment]
@israelvicars the release 0.1.8 (https://github.com/Quansight/omnisci-datascience-installer/releases/tag/0.1.8) has already the installer for linux. The CI already ran some tests, but we need to run more tests locally.

PS: @israelvicars it seems I don't have access to https://omnisci.atlassian.net/browse/FE-13235

cc @anirrudh

**Comment by xmnlab** [comment]
@israelvicars I am closing this issue for now, let me know if there is anything else you want for the linux installer.
