### ISSUE TITLE
Automatically build and publish installer

### ISSUE THREAD

**Issue by dharhas** [Quansight/omnisci-datascience-installer#8]
Can we setup Github Actions to build any time the construct.yaml is chaned and then publish though something like https://github.com/features/packages? @xmnlab can you look at this with @scopatz guidance?

**Comment by scopatz** [comment]
I would start with a github action for this that then runs on merge

**Comment by scopatz** [comment]
I have added some usage instructions to the readme and also you may want to start from Gonzalo's github action for getting a conda env up and running.

**Comment by xmnlab** [comment]
sounds great! thanks, @scopatz !!

**Comment by xmnlab** [comment]
hey @dharhas I was checking github packages. 

as far as I understood, currently, github packages just works for: docker images, npm, gem, mvn and nugget (https://docs.github.com/en/packages/publishing-and-managing-packages/about-github-packages#support-for-package-registries).

do you want something specific related to github packages? or would github releases work for what you want?

thanks!

**Comment by dharhas** [comment]
Anything that lets us automatically post the installer somewhere for download.

**Comment by rpekrul** [comment]
@kcpevey Can you take a look?
